version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/aws:2023.04.1
    steps:
      - checkout
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id *************
            aws configure set aws_secret_access_key ******************
            aws configure set ************
      - run:
          name: Let's deploy this application
          command: |
            ls
            aws s3 sync . s3://me-bucket-name/

workflows:
  Production:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
